buildable_serializer:
    paths:
        "App\\Model":
            path: "%kernel.project_dir%/src/Model"
            exclude:
                - "*ModelHelperClass.php"

    features:
        groups: true
        max_depth: true
        circular_reference: true
        name_converter: false
        skip_null_values: true

    generation:
        strict_types: true
